name: remindersplus
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  image_path: "assets/app/icon/icon.png"

  android: "launcher_icon"
  min_sdk_android: 21
  # adaptive_icon_background: "assets/app/icon/background.png"
  # adaptive_icon_foreground: "assets/app/icon/foreground.png"

  ios: true
  remove_alpha_ios: true

  web:
    generate: true
    image_path: "assets/app/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"

  windows:
    generate: true
    image_path: "assets/app/icon/icon.png"
    icon_size: 48

  macos:
    generate: true
    image_path: "assets/app/icon/icon.png"

  linux:
    generate: true
    image_path: "assets/app/icon/icon.png"